name: shared
description: Shared models and utilities for Mali Matrimony project.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  postgres: ^3.0.2
  flutter_dotenv: ^5.1.0
