name: shared
description: Shared models and utilities for Mali Matrimony project.
version: 0.7.0
publish_to: 'none'

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  postgres: ^3.0.2
  flutter_dotenv: ^5.1.0
  http: ^1.1.0
  image_picker: ^1.0.4
  intl: ^0.20.2

flutter:
  assets:
    - assets/.env
